[package]
name = "engine-io"
version = "0.1.0"
authors = ["Vibhav Pant <vibhavp@gmail.com>"]
license = "MIT"

[dependencies]
iron = "0.4.0"
rand = "0.3"
url = "1.1.1"
rust-crypto = "0.2.36"
rustc-serialize = "0.3"
modifier = "0.1.0"
cookie = "0.2.5"
time = "0.1.35"
hyper = "0.9.10"
log = "0.3.6"